### ISSUE TITLE
Try using BouncyCastle.Net for their implementation of BigInteger.

### ISSUE THREAD

**Issue by KieranFoot** [dorianmuthig/SSSsharp#1]
If you are having issues with BigInteger, try and use the .Net implementation of the BouncyCastle Crypto library, which has it's own implementation.

**Comment by dori4n** [comment]
No, the whole point of this exercise was to use official .NET types or ship the component source code with the application. Getting a working application out of it wasn't really the biggest priority anyway, since a working C implementation already exists. This is a port after all.

**Comment by KieranFoot** [comment]
So it was an exercise in making a port that does not function?

**Comment by dori4n** [comment]
It may not depend on anything not in the standard .NET framework unless licensing allows shipping the code _with_ the code of the application. That might mean yes.
